lti-test-tool:
  build: .
  command: bundle exec rails s -p 8080
  volumes:
    - .:/usr/src/app
  ports:
    - "8080:8080"
  environment:
    VIRTUAL_HOST: lti.docker
    DATABASE_URL: postgres://postgres@db:5432
  links:
    - db

db:
  image: postgres
