test:
  adapter: postgresql
  database: lti_tool_provider_example_test

development:
  adapter: postgresql
  encoding: utf8
  database: lti_tool_provider_example_development

production:
  adapter: postgresql
  encoding: utf8
  database: lti_tool_provider_example_production
  timeout: 5000
  connect_timeout: 10
